package fr.cotedazur.univ.polytech.ttr.equipeb.controllers;

public enum ReasonActionRefused {
    ACTION_INVALID,
    DESTINATION_CARDS_DECK_EMPTY,
    DESTINATION_CARDS_CHOSEN_CARDS_EMPTY,
    ROUTE_INVALID,
    ROUTE_WANTED_ROUTE_NOT_FOUND,
    ROUTE_WANTED_ROUTE_ALREADY_CLAIMED,
    ROUTE_WRONG_GIVEN_WAGON_CARDS_SIZE,
    ROUTE_NOT_ENOUGH_WAGON_CARDS,
    ROUTE_FERRY_NOT_ENOUGH_LOCOMOTIVES,
    ROUTE_FERRY_WRONG_WAGON_CARDS_COLOR,
    ROUTE_TRAIN_WRONG_WAGON_CARDS_COLOR,
    ROUTE_TUNNEL_WRONG_WAGON_CARDS_COLOR,
    ROUTE_TUNNEL_NOT_ENOUGH_WAGON_CARDS,
    ROUTE_TUNNEL_NOT_ENOUGH_REMOVED_WAGON_CARDS,
    ROUTE_UNKNOW_TYPE,
    STATION_NOT_ENOUGH_STATIONS_LEFT,
    STATION_CITY_NOT_VALID,
    STATION_NOT_ENOUGH_WAGON_CARDS,
    STATION_WRONG_WAGON_CARDS_COLOR,
    WAGON_CARDS_DECK_EMPTY,
}
